{{- if .Values.apiserver.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kdp-oam-operator.fullname" . }}-apiserver
  labels:
  {{- include "kdp-oam-apiserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiserver.service.type }}
  ports:
    - port: {{ .Values.apiserver.service.port }}
      targetPort: {{ .Values.apiserver.service.port }}
      protocol: TCP
      name: server
  selector:
  {{- include "kdp-oam-apiserver.selectorLabels" . | nindent 4 }}
{{- end }}