---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-bdc-kdp-io-v1alpha1-bigdatacluster
  failurePolicy: Fail
  name: mbigdatacluster.kb.io
  rules:
  - apiGroups:
    - bdc.kdp.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bigdataclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-bdc-kdp-io-v1alpha1-contextsecret
  failurePolicy: Fail
  name: mcontextsecret.kb.io
  rules:
  - apiGroups:
    - bdc.kdp.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - contextsecrets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-bdc-kdp-io-v1alpha1-contextsetting
  failurePolicy: Fail
  name: mcontextsetting.kb.io
  rules:
  - apiGroups:
    - bdc.kdp.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - contextsettings
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-bdc-kdp-io-v1alpha1-bigdatacluster
  failurePolicy: Fail
  name: vbigdatacluster.kb.io
  rules:
  - apiGroups:
    - bdc.kdp.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bigdataclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-bdc-kdp-io-v1alpha1-contextsecret
  failurePolicy: Fail
  name: vcontextsecret.kb.io
  rules:
  - apiGroups:
    - bdc.kdp.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - contextsecrets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-bdc-kdp-io-v1alpha1-contextsetting
  failurePolicy: Fail
  name: vcontextsetting.kb.io
  rules:
  - apiGroups:
    - bdc.kdp.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - contextsettings
  sideEffects: None
