# permissions for end users to view bigdataclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bigdatacluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kdp-oam-operator
    app.kubernetes.io/part-of: kdp-oam-operator
    app.kubernetes.io/managed-by: kustomize
  name: bigdatacluster-viewer-role
rules:
- apiGroups:
  - bdc.kdp.io
  resources:
  - bigdataclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bdc.kdp.io
  resources:
  - bigdataclusters/status
  verbs:
  - get
