---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - bdc.kdp.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bdc.kdp.io
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - bdc.kdp.io
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bdc.kdp.io
  resources:
  - bigdataclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bdc.kdp.io
  resources:
  - bigdataclusters/finalizers
  verbs:
  - update
- apiGroups:
  - bdc.kdp.io
  resources:
  - bigdataclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bdc.kdp.io
  resources:
  - contextsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bdc.kdp.io
  resources:
  - contextsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - bdc.kdp.io
  resources:
  - contextsecrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bdc.kdp.io
  resources:
  - contextsettings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bdc.kdp.io
  resources:
  - contextsettings/finalizers
  verbs:
  - update
- apiGroups:
  - bdc.kdp.io
  resources:
  - contextsettings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bdc.kdp.io
  resources:
  - xdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bdc.kdp.io
  resources:
  - xdefinitions/finalizers
  verbs:
  - update
- apiGroups:
  - bdc.kdp.io
  resources:
  - xdefinitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.oam.dev/v1beta1
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
