{{- if and .Values.admissionWebhooks.certManager.enabled -}}
# The following manifests contain a self-signed issuer CR and a certificate CR.
# More document can be found at https://docs.cert-manager.io
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "kdp-oam-operator.fullname" . }}-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kdp-oam-operator.fullname" . }}-serving-cert
spec:
  dnsNames:
    - {{ include "kdp-oam-operator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
    - {{ include "kdp-oam-operator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "kdp-oam-operator.fullname" . }}-selfsigned-issuer
  secretName: {{ template "kdp-oam-operator.fullname" . }}-webhook-server-cert
{{- end }}
