{{- if .Values.admissionWebhooks.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kdp-oam-operator.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kdp-oam-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.admissionWebhooks.service.type }}
  ports:
    - port: 443
      targetPort: {{ .Values.admissionWebhooks.service.port }}
      protocol: TCP
      name: https
  selector:
    {{ include "kdp-oam-operator.selectorLabels" . | nindent 6 }}
{{- end -}}
