apiVersion: bdc.kdp.io/v1alpha1
kind: XDefinition
metadata:
  annotations:
    definition.bdc.kdp.io/description: Init context secret resource
  name: contextsecret-def
spec:
  apiResource:
    definition:
      apiVersion: bdc.kdp.io/v1alpha1
      kind: ContextSecret
  schematic:
    cue:
      template: |
        output: {
            apiVersion: "v1"
            kind:       "Secret"
            metadata: {
                name:      parameter.name
                namespace: context.namespace
                annotations: "bdc.kdp.io/name": context.bdcName
            }
            type: "Opaque"
            data: parameter.data
        }

        parameter: {
            // Specify context secret name
            name: string
            // Specify context secret data
            data: [string]: string | int | float
        }
