# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/bdc.kdp.io_bigdataclusters.yaml
- bases/bdc.kdp.io_contextsecrets.yaml
- bases/bdc.kdp.io_contextsettings.yaml
- bases/bdc.kdp.io_customsecrets.yaml
- bases/bdc.kdp.io_customsettings.yaml
- bases/bdc.kdp.io_resourcecontrols.yaml
- bases/bdc.kdp.io_orgresourcecontrols.yaml
- bases/bdc.kdp.io_xdefinitions.yaml
- bases/bdc.kdp.io_applications.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_bigdataclusters.yaml
#- patches/webhook_in_contextsecrets.yaml
#- patches/webhook_in_contextsettings.yaml
#- patches/webhook_in_customsecrets.yaml
#- patches/webhook_in_customsettings.yaml
#- patches/webhook_in_resourcecontrols.yaml
#- patches/webhook_in_orgresourcecontrols.yaml
#- patches/webhook_in_xdefinitions.yaml
#- patches/webhook_in_applications.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_bigdataclusters.yaml
#- patches/cainjection_in_contextsecrets.yaml
#- patches/cainjection_in_contextsettings.yaml
#- patches/cainjection_in_customsecrets.yaml
#- patches/cainjection_in_customsettings.yaml
#- patches/cainjection_in_resourcecontrols.yaml
#- patches/cainjection_in_orgresourcecontrols.yaml
#- patches/cainjection_in_xdefinitions.yaml
#- patches/cainjection_in_applications.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
