# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI-Build

on:
  release:
    types:
      - published
    tags:
      - v*

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASSWD }}

      - name: Build Images
        run: |
          make docker-build IMG_REGISTRY=${{ secrets.CONTAINER_REGISTRY }}

      - name: Push Images
        run: |
          make docker-push IMG_REGISTRY=${{ secrets.CONTAINER_REGISTRY }}
